version: '3'
services:
  protranslating-backend:
    container_name: protranslating-backend
    image: protranslating
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - '27018:27017'
